const fs = require('fs');
const path = require('path');
const vm = require('vm');
const assert = require('node:assert/strict');
const ts = require('typescript');
const root = path.resolve(__dirname, '..');
const taxonomy = require('../lib/report-taxonomy.json');
const code = ts.transpileModule(fs.readFileSync(path.join(root,'lib/reports.ts'),'utf8'), {compilerOptions:{module:ts.ModuleKind.CommonJS,esModuleInterop:true}}).outputText;
const output={};
vm.runInNewContext(code,{exports:output,require:name=>{assert.equal(name,'./report-taxonomy.json');return taxonomy;}});
const domainRows=taxonomy.domains.map(d=>({...d,low:10,high:20,grade:'D'})).reverse();
assert.equal(JSON.stringify(output.orderedDomains(domainRows).map(d=>d.key)),JSON.stringify(taxonomy.domains.map(d=>d.key)));
assert.equal(domainRows[0].key,'listening');
const rows=taxonomy.types.map(t=>({...t,correct:2,total:4,averageSeconds:1.5,grade:'D'})).reverse();
assert.equal(JSON.stringify(output.orderedTypes(rows).map(d=>d.key)),JSON.stringify(taxonomy.types.map(d=>d.key)));
assert.equal(output.orderedTypes([]).length,10);
assert.equal(output.formatAccuracy({correct:0,total:0}),'未実施');
assert.equal(output.formatAccuracy({correct:0,total:4}),'0/4 (0%)');
assert.equal(output.formatAccuracy({correct:2,total:4}),'2/4 (50%)');
assert.equal(output.formatClock(null),'未計測');
assert.equal(output.formatClock(683),'11:23');
assert.equal(output.formatStudy(192),'3時間12分');
const page=fs.readFileSync(path.join(root,'app/page.tsx'),'utf8');
assert(!page.includes('学習完了'));
assert(!page.includes('自作テストの累積値'));
assert(!page.includes('const fallback'));
assert(page.includes('row.cumulative'));
assert(page.includes('selected?.anki'));
assert(page.includes('forecast.tomorrowDue'));
console.log('PASS: fixed display order, immutable inputs, missing/zero distinctions, timing formats, removed misleading labels and fallback');
