# -*- coding: utf-8 -*-
"""Comprehensive list and card builder for Japanese Exception Group 1 Verbs (예외 1그룹 동사 마스터)."""
import sys, json

sys.stdout.reconfigure(encoding='utf-8')

# CSS Block (Consistent with high-contrast light/dark mode design in project)
CSS_BLOCK = """<style>
.vt-wrap { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; line-height: 1.6; text-align: left; max-width: 540px; margin: 0 auto; box-sizing: border-box; }
.vt-center { text-align: center; }
.vt-title { font-size: 28px; font-weight: 800; margin: 14px 0 8px 0; color: #0f172a; letter-spacing: -0.5px; }
.vt-sub { font-size: 15px; color: #475569; font-weight: 500; }
.vt-badge { display: inline-block; font-size: 12px; font-weight: 700; border-radius: 6px; padding: 3px 10px; margin-bottom: 8px; }
.vt-badge-grp { color: #b45309; background: #fef3c7; border: 1px solid #fde68a; }
.vt-badge-irreg { color: #b91c1c; background: #fee2e2; border: 1px solid #fecaca; }
.vt-ans-head { font-size: 22px; font-weight: 800; color: #047857; margin-bottom: 12px; text-align: center; background: #ecfdf5; padding: 10px; border-radius: 8px; border: 1px solid #a7f3d0; }
.vt-sec { border-left: 4px solid #10b981; background: #f0fdf4; border-radius: 0 8px 8px 0; padding: 12px 14px; margin-bottom: 12px; }
.vt-sec-contrast { border-left: 4px solid #f59e0b; background: #fffbeb; border-radius: 0 8px 8px 0; padding: 12px 14px; margin-bottom: 12px; }
.vt-meaning { font-size: 16px; font-weight: 700; color: #065f46; margin-bottom: 4px; }
.vt-rule-box { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 12px 14px; margin-top: 10px; }
.vt-rule-title { font-weight: 700; font-size: 14px; color: #1e293b; margin-bottom: 6px; }
.vt-rule-content { font-size: 13.5px; color: #334155; line-height: 1.6; }
.vt-ex-ja { font-size: 15px; color: #0f172a; margin-top: 6px; font-weight: 600; }
.vt-ex-ko { font-size: 13.5px; color: #64748b; margin-top: 2px; }
.vt-tag { color: #475569; font-weight: 700; margin-right: 4px; }
.vt-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 6px; margin-top: 6px; font-size: 13px; }
.vt-grid-item { background: #ffffff; padding: 6px 8px; border-radius: 4px; border: 1px solid #e2e8f0; }

html.nightMode body.nightMode .vt-title,
html.night_mode body.night_mode .vt-title { color: #f8fafc !important; }
html.nightMode body.nightMode .vt-sub,
html.night_mode body.night_mode .vt-sub { color: #cbd5e1 !important; }
html.nightMode body.nightMode .vt-meaning,
html.night_mode body.night_mode .vt-meaning { color: #34d399 !important; }
html.nightMode body.nightMode .vt-sec,
html.night_mode body.night_mode .vt-sec { background: rgba(16, 185, 129, 0.12) !important; border-left-color: #10b981 !important; }
html.nightMode body.nightMode .vt-sec-contrast,
html.night_mode body.night_mode .vt-sec-contrast { background: rgba(245, 158, 11, 0.12) !important; border-left-color: #f59e0b !important; }
html.nightMode body.nightMode .vt-rule-box,
html.night_mode body.night_mode .vt-rule-box { background: #1e293b !important; border-color: #334155 !important; }
html.nightMode body.nightMode .vt-rule-title,
html.night_mode body.night_mode .vt-rule-title { color: #f8fafc !important; }
html.nightMode body.nightMode .vt-rule-content,
html.night_mode body.night_mode .vt-rule-content { color: #cbd5e1 !important; }
html.nightMode body.nightMode .vt-grid-item,
html.night_mode body.night_mode .vt-grid-item { background: #0f172a !important; border-color: #334155 !important; color: #f8fafc !important; }
html.nightMode body.nightMode .vt-ex-ja,
html.night_mode body.night_mode .vt-ex-ja { color: #f8fafc !important; }
html.nightMode body.nightMode .vt-ex-ko,
html.night_mode body.night_mode .vt-ex-ko { color: #94a3b8 !important; }
</style>"""

# 30 Curated Exception Group 1 Verbs
# All end in -iru or -eru, look like Group 2, but conjugate strictly as Group 1 (5-dan)!
EXCEPTION_VERBS = [
    {
        "kanji": "帰る",
        "reading": "かえる",
        "meaning": "돌아가다, 돌아오다",
        "category": "-える 형태 (외형 2그룹 -> 실질 1그룹)",
        "contrast": "変える (바꾸다, 2그룹) / 換える (바꾸다, 2그룹)와 구별 필수!",
        "masu": "帰ります (かえります)",
        "nai": "帰らない (かえらない)",
        "te": "帰って (かえって - 촉음편)",
        "ta": "帰った (かえった)",
        "ba": "帰れば (かえれば)",
        "kanou": "帰れる (かえれる)",
        "shieki": "帰らせる (かえらせる)",
        "ukemi": "帰られる (かえられる)",
        "ex_ja": "用事を済ませて、急いで家に帰った。",
        "ex_ko": "볼일을 마치고 서둘러 집으로 돌아갔다."
    },
    {
        "kanji": "入る",
        "reading": "はいる",
        "meaning": "들어가다, 들어오다",
        "category": "-いる 형태 (외형 2그룹 -> 실질 1그룹)",
        "contrast": "入れる (넣다, 2그룹 타동사: いれます)와 구별 필수!",
        "masu": "入ります (はいります)",
        "nai": "入らない (はいらない)",
        "te": "入って (はいって - 촉음편)",
        "ta": "入った (はいった)",
        "ba": "入れば (はいれば)",
        "kanou": "入れる (はいれる)",
        "shieki": "入らせる (はいらせる)",
        "ukemi": "入られる (はいられる)",
        "ex_ja": "靴を脱いで部屋に入ってください。",
        "ex_ko": "신발을 벗고 방으로 들어가세요."
    },
    {
        "kanji": "走る",
        "reading": "はしる",
        "meaning": "달리다",
        "category": "-いる 형태 (외형 2그룹 -> 실질 1그룹)",
        "contrast": "2그룹 동사(はします X)로 오인하기 쉬운 대표 기초 필수 동사!",
        "masu": "走ります (はしります)",
        "nai": "走らない (はしらない)",
        "te": "走って (はしって - 촉음편)",
        "ta": "走った (はしった)",
        "ba": "走れば (はしれば)",
        "kanou": "走れる (はしれる)",
        "shieki": "走らせる (はしらせる)",
        "ukemi": "走られる (はしられる)",
        "ex_ja": "毎朝公園の周りを軽く走っている。",
        "ex_ko": "매일 아침 공원 주변을 가볍게 달리고 있다."
    },
    {
        "kanji": "切る",
        "reading": "きる",
        "meaning": "자르다, 끊다",
        "category": "-いる 형태 (외형 2그룹 -> 실질 1그룹)",
        "contrast": "着る (입다, 2그룹: きます/きない/きて)와 발음은 같으나 활용 완전 대조!",
        "masu": "切ります (きります)",
        "nai": "切らない (きらない)",
        "te": "切って (きって - 촉음편)",
        "ta": "切った (きった)",
        "ba": "切れば (きれば)",
        "kanou": "切れる (きれる - 1그룹 가능형/자동사)",
        "shieki": "切らせる (きらせる)",
        "ukemi": "切られる (きられる)",
        "ex_ja": "ハサミで紙をきれいに切った。",
        "ex_ko": "가위로 종이를 깨끗하게 잘랐다."
    },
    {
        "kanji": "知る",
        "reading": "しる",
        "meaning": "알다",
        "category": "-いる 형태 (외형 2그룹 -> 실질 1그룹)",
        "contrast": "상태 표현: 知っている(알고 있다) / 부정 표현: 知らない(모른다, 知っていない X)",
        "masu": "知ります (しります)",
        "nai": "知らない (しらない)",
        "te": "知って (しって - 촉음편)",
        "ta": "知った (しった)",
        "ba": "知れば (しれば)",
        "kanou": "知れる (しれる)",
        "shieki": "知らせる (しらせる - 알리다/통지하다)",
        "ukemi": "知られる (しられる - 알려지다)",
        "ex_ja": "そのニュースの真相はまだ誰も知らない。",
        "ex_ko": "그 뉴스의 진상은 아직 아무도 모른다."
    },
    {
        "kanji": "要る",
        "reading": "いる",
        "meaning": "필요하다",
        "category": "-いる 형태 (외형 2그룹 -> 실질 1그룹)",
        "contrast": "居る (있다, 2그룹: います/いない/いて)와 발음은 같으나 활용 완전 대조!",
        "masu": "要ります (いります)",
        "nai": "要らない (いらない)",
        "te": "要って (いって - 촉음편)",
        "ta": "要った (いった)",
        "ba": "要れば (いれば)",
        "kanou": "要れる (いれる)",
        "shieki": "要らせる (いらせる)",
        "ukemi": "要られる (いられる)",
        "ex_ja": "海外旅行にはパスポートが絶対に要る。",
        "ex_ko": "해외여행에는 여권이 절대로 필요하다."
    },
    {
        "kanji": "減る",
        "reading": "へる",
        "meaning": "줄다, 감소하다",
        "category": "-える 형태 (외형 2그룹 -> 실질 1그룹)",
        "contrast": "N2 시험 빈출! 減る(1그룹 자동사) vs 減らす(1그룹 타동사: 줄이다)",
        "masu": "減ります (へります)",
        "nai": "減らない (へらない)",
        "te": "減って (へって - 촉음편)",
        "ta": "減った (へった)",
        "ba": "減れば (へれば)",
        "kanou": "減れる (へれる)",
        "shieki": "減らせる (へらせる)",
        "ukemi": "減られる (へられる)",
        "ex_ja": "不景気で会社の売上が大幅に減った。",
        "ex_ko": "불경기로 회사의 매출이 대폭 줄었다."
    },
    {
        "kanji": "喋る",
        "reading": "しゃべる",
        "meaning": "지껄이다, 수다 떨다, 말하다",
        "category": "-える 형태 (외형 2그룹 -> 실질 1그룹)",
        "contrast": "しゃべります / しゃべらない / しゃべって (1그룹 촉음편!)",
        "masu": "喋ります (しゃべります)",
        "nai": "喋らない (しゃべらない)",
        "te": "喋って (しゃべって - 촉음편)",
        "ta": "喋った (しゃべった)",
        "ba": "喋れば (しゃべれば)",
        "kanou": "喋れる (しゃべれる)",
        "shieki": "喋らせる (しゃべらせる)",
        "ukemi": "喋られる (しゃべられる)",
        "ex_ja": "授業中に隣の席の人と喋ってはいけない。",
        "ex_ko": "수업 중에 옆자리 사람과 수다를 떨어서는 안 된다."
    },
    {
        "kanji": "滑る",
        "reading": "すべる",
        "meaning": "미끄러지다, 미끄러져 떨어지다",
        "category": "-える 형태 (외형 2그룹 -> 실질 1그룹)",
        "contrast": "すべります / すべって / すべった (시험에서 떨어지다 비유로도 빈출)",
        "masu": "滑ります (すべります)",
        "nai": "滑らない (すべらない)",
        "te": "滑って (すべって - 촉음편)",
        "ta": "滑った (すべった)",
        "ba": "滑れば (すべれば)",
        "kanou": "滑れる (すべれる)",
        "shieki": "滑らせる (すべらせる)",
        "ukemi": "滑られる (すべられる)",
        "ex_ja": "凍った雪道で足が滑って転んでしまった。",
        "ex_ko": "얼어붙은 눈길에서 발이 미끄러져 넘어지고 말았다."
    },
    {
        "kanji": "限る",
        "reading": "かぎる",
        "meaning": "한하다, 한정하다",
        "category": "-いる 형태 (외형 2그룹 -> 실질 1그룹)",
        "contrast": "N2 핵심 문형: 〜に限る (~이 최고다) / 〜とは限らない (반드시 ~인 것은 아니다)",
        "masu": "限ります (かぎります)",
        "nai": "限らない (かぎらない)",
        "te": "限って (かぎって - 촉음편)",
        "ta": "限った (かぎった)",
        "ba": "限れば (かぎれば)",
        "kanou": "限れる (かぎれる)",
        "shieki": "限らせる (かぎらせる)",
        "ukemi": "限られる (かぎられる)",
        "ex_ja": "夏の暑い日には冷たい麦茶を飲むに限る。",
        "ex_ko": "여름의 무더운 날에는 시원한 보리차를 마시는 것이 최고다."
    },
    {
        "kanji": "散る",
        "reading": "ちる",
        "meaning": "떨어지다, 흩어지다",
        "category": "-いる 형태 (외형 2그룹 -> 실질 1그룹)",
        "contrast": "花が散る(꽃이 지다), 気が散る(마음이 산만해지다). ちります / ちって!",
        "masu": "散ります (ちります)",
        "nai": "散らない (ちらない)",
        "te": "散って (ちって - 촉음편)",
        "ta": "散った (ちった)",
        "ba": "散れば (ちれば)",
        "kanou": "散れる (ちれる)",
        "shieki": "散らせる (ちらせる)",
        "ukemi": "散られる (ちられる)",
        "ex_ja": "強い風が吹いて、桜の花びらが一斉に散った。",
        "ex_ko": "강한 바람이 불어 벚꽃 잎이 일제히 흩날려 떨어졌다."
    },
    {
        "kanji": "照る",
        "reading": "てる",
        "meaning": "비치다, 햇살이 내리쬐다",
        "category": "-える 형태 (외형 2그룹 -> 실질 1그룹)",
        "contrast": "照らす(비추다, 1그룹 타동사) vs 照る(비치다, 1그룹 자동사)",
        "masu": "照ります (てります)",
        "nai": "照らない (てらない)",
        "te": "照って (てって - 촉음편)",
        "ta": "照った (てった)",
        "ba": "照れば (てれば)",
        "kanou": "照れる (てれる - 부끄러워하다, 수줍어하다)",
        "shieki": "照らせる (てらせる)",
        "ukemi": "照られる (てられる)",
        "ex_ja": "雨がやんで、青空に日が照ってきた。",
        "ex_ko": "비가 그치고 푸른 하늘에 햇살이 내리쬐기 시작했다."
    },
    {
        "kanji": "蹴る",
        "reading": "ける",
        "meaning": "차다, 걷어차다, 거절하다",
        "category": "-える 형태 (외형 2그룹 -> 실질 1그룹)",
        "contrast": "1글자 어간+る 동사 중 대표적 1그룹 예외! けります / けって / けった",
        "masu": "蹴ります (けります)",
        "nai": "蹴らない (けらない)",
        "te": "蹴って (けって - 촉음편)",
        "ta": "蹴った (けった)",
        "ba": "蹴れば (ければ)",
        "kanou": "蹴れる (けれる)",
        "shieki": "蹴らせる (けらせる)",
        "ukemi": "蹴られる (けられる)",
        "ex_ja": "ボールを強く蹴ってゴールに入れた。",
        "ex_ko": "공을 강하게 차서 골대에 넣었다."
    },
    {
        "kanji": "握る",
        "reading": "にぎる",
        "meaning": "쥐다, 잡다, 쥐고 흔들다",
        "category": "-いる 형태 (외형 2그룹 -> 실질 1그룹)",
        "contrast": "おにぎり(주먹밥), 手を握る(손을 잡다). にぎります / にぎって!",
        "masu": "握ります (にぎります)",
        "nai": "握らない (にぎらない)",
        "te": "握って (にぎって - 촉음편)",
        "ta": "握った (にぎった)",
        "ba": "握れば (にぎれば)",
        "kanou": "握れる (にぎれる)",
        "shieki": "握らせる (にぎらせる)",
        "ukemi": "握られる (にぎられる)",
        "ex_ja": "彼は固く拳を握りしめて決意を固めた。",
        "ex_ko": "그는 주먹을 불끈 쥐고 결의를 다졌다."
    },
    {
        "kanji": "焦る",
        "reading": "あせる",
        "meaning": "안달하다, 초조해하다, 서두르다",
        "category": "-える 형태 (외형 2그룹 -> 실질 1그룹)",
        "contrast": "N2 독해/청해 빈출! 焦る(1그룹 예외: あせります / あせらない / あせって)",
        "masu": "焦ります (あせります)",
        "nai": "焦らない (あせらない)",
        "te": "焦って (あせって - 촉음편)",
        "ta": "焦った (あせった)",
        "ba": "焦れば (あせれば)",
        "kanou": "焦れる (あせれる)",
        "shieki": "焦らせる (あせらせる)",
        "ukemi": "焦られる (あせられる)",
        "ex_ja": "時間が足りなくなっても、決して焦ってはいけない。",
        "ex_ko": "시간이 부족해지더라도 결코 초조해해서는 안 된다."
    },
    {
        "kanji": "練る",
        "reading": "ねる",
        "meaning": "반죽하다, (계획·문장을) 가다듬다/짜다",
        "category": "-える 형태 (외형 2그룹 -> 실질 1그룹)",
        "contrast": "寝る (자다, 2그룹: ねます/ねない/ねて)와 한자 및 활용 구분 필수!",
        "masu": "練ります (ねります)",
        "nai": "練らない (ねらない)",
        "te": "練って (ねって - 촉음편)",
        "ta": "練った (ねった)",
        "ba": "練れば (ねれば)",
        "kanou": "練れる (ねれる)",
        "shieki": "練らせる (ねらせる)",
        "ukemi": "練られる (ねられる)",
        "ex_ja": "新事業の計画を徹底的に練り直した。",
        "ex_ko": "신규 사업의 계획을 철저하게 다시 가다듬었다."
    },
    {
        "kanji": "遮る",
        "reading": "さえぎる",
        "meaning": "가로막다, 차단하다, 가리다",
        "category": "-いる 형태 (외형 2그룹 -> 실질 1그룹)",
        "contrast": "N2 어휘 빈출! 話を遮る(말을 가로막다), 光を遮る(빛을 차단하다)",
        "masu": "遮ります (さえぎります)",
        "nai": "遮らない (さえぎらない)",
        "te": "遮って (さえぎって - 촉음편)",
        "ta": "遮った (さえぎった)",
        "ba": "遮れば (さえぎれば)",
        "kanou": "遮れる (さえぎれる)",
        "shieki": "遮らせる (さえぎらせる)",
        "ukemi": "遮られる (さえぎられる)",
        "ex_ja": "人の話を途中で遮るのは失礼な態度だ。",
        "ex_ko": "남의 말을 도중에 가로막는 것은 실례되는 태도다."
    },
    {
        "kanji": "覆る",
        "reading": "くつがえる",
        "meaning": "뒤집히다, 번복되다",
        "category": "-える 형태 (외형 2그룹 -> 실질 1그룹)",
        "contrast": "N2 독해 핵심! 判決が覆る(판결이 뒤집히다), 定説が覆る(정설이 뒤집히다)",
        "masu": "覆ります (くつがえります)",
        "nai": "覆らない (くつがえらない)",
        "te": "覆って (くつがえって - 촉음편)",
        "ta": "覆った (くつがえった)",
        "ba": "覆れば (くつがえれば)",
        "kanou": "覆れる (くつがえれる)",
        "shieki": "覆らせる (くつがえらせる)",
        "ukemi": "覆られる (くつがえられる)",
        "ex_ja": "裁判でこれまでの常識が根底から覆った。",
        "ex_ko": "재판에서 지금까지의 상식이 근본부터 뒤집혔다."
    },
    {
        "kanji": "蘇る",
        "reading": "よみがえる",
        "meaning": "되살아나다, 소생하다",
        "category": "-える 형태 (외형 2그룹 -> 실질 1그룹)",
        "contrast": "N2 독해 빈출! 記憶が蘇る(기억이 되살아나다). よみがえります / よみがえって",
        "masu": "蘇ります (よみがえります)",
        "nai": "蘇らない (よみがえらない)",
        "te": "蘇って (よみがえって - 촉음편)",
        "ta": "蘇った (よみがえった)",
        "ba": "蘇れば (よみがえれば)",
        "kanou": "蘇れる (よみがえれる)",
        "shieki": "蘇らせる (よみがえらせる)",
        "ukemi": "蘇られる (よみがえられる)",
        "ex_ja": "昔の写真を見て、当時の懐かしい思い出が蘇った。",
        "ex_ko": "옛날 사진을 보고 당시의 그리운 추억이 되살아났다."
    },
    {
        "kanji": "千切る",
        "reading": "ちぎる",
        "meaning": "잘게 뜯다, 찢다, 뜯어내다",
        "category": "-いる 형태 (외형 2그룹 -> 실질 1그룹)",
        "contrast": "契る(치기루: 맹세하다)와 구별. パンを千切る(빵을 뜯다). ちぎります / ちぎって",
        "masu": "千切ります (ちぎります)",
        "nai": "千切らない (ちぎらない)",
        "te": "千切って (ちぎって - 촉음편)",
        "ta": "千切った (ちぎった)",
        "ba": "千切れば (ちぎれば)",
        "kanou": "千切れる (ちぎれる - 뜯어지다/끊어지다, 자동사)",
        "shieki": "千切らせる (ちぎらせる)",
        "ukemi": "千切られる (ちぎられる)",
        "ex_ja": "キャベツの葉を手で小さく千切ってサラダに入れた。",
        "ex_ko": "양배추 잎을 손으로 잘게 뜯어 샐러드에 넣었다."
    },
    {
        "kanji": "齧る",
        "reading": "かじる",
        "meaning": "베어 물다, 갉아먹다, 겉핥다/조금 배우다",
        "category": "-いる 형태 (외형 2그룹 -> 실질 1그룹)",
        "contrast": "친숙한 관용구: 親のすねをかじる(부모에게 얹혀살다), フランス語をかじる(불어를 수박 겉핥다)",
        "masu": "齧ります (かじります)",
        "nai": "齧らない (かじらない)",
        "te": "齧って (かじって - 촉음편)",
        "ta": "齧った (かじった)",
        "ba": "齧れば (かじれば)",
        "kanou": "齧れる (かじれる)",
        "shieki": "齧らせる (かじらせる)",
        "ukemi": "齧られる (かじられる)",
        "ex_ja": "リンゴを丸ごとかじりながら歩いた。",
        "ex_ko": "사과를 통째로 베어 물면서 걸었다."
    },
    {
        "kanji": "茂る",
        "reading": "しげる",
        "meaning": "우거지다, 무성하다",
        "category": "-える 형태 (외형 2그룹 -> 실질 1그룹)",
        "contrast": "草木が茂る(풀과 나무가 무성하다). しげります / しげらない / しげって",
        "masu": "茂ります (しげります)",
        "nai": "茂らない (しげらない)",
        "te": "茂って (しげって - 촉음편)",
        "ta": "茂った (しげった)",
        "ba": "茂れば (しげれば)",
        "kanou": "茂れる (しげれる)",
        "shieki": "茂らせる (しげらせる)",
        "ukemi": "茂られる (しげられる)",
        "ex_ja": "夏になると庭の木々の葉が青々と茂る。",
        "ex_ko": "여름이 되면 마당 나무들의 잎이 푸르게 우거진다."
    },
    {
        "kanji": "湿る",
        "reading": "しめる",
        "meaning": "축축해지다, 눅눅해지다",
        "category": "-える 형태 (외형 2그룹 -> 실질 1그룹)",
        "contrast": "閉める(닫다, 2그룹: しめます/しめて) / 占める(차지하다, 2그룹)와 구별 필수!",
        "masu": "湿ります (しめります)",
        "nai": "湿らない (しめらない)",
        "te": "湿って (しめって - 촉음편)",
        "ta": "湿った (しめった)",
        "ba": "湿れば (しめれば)",
        "kanou": "湿れる (しめれる)",
        "shieki": "湿らせる (しめらせる - 적시다)",
        "ukemi": "湿られる (しめられる)",
        "ex_ja": "雨のせいで部屋の空気が湿っている。",
        "ex_ko": "비 때문에 방 안 공기가 눅눅하다."
    },
    {
        "kanji": "捻る",
        "reading": "ひねる",
        "meaning": "비틀다, 틀다, 머리를 짜내다",
        "category": "-える 형태 (외형 2그룹 -> 실질 1그룹)",
        "contrast": "蛇口をひねる(수도꼭지를 틀다), 頭をひねる(머리를 짜내다). ひねります / ひねって",
        "masu": "捻ります (ひねります)",
        "nai": "捻らない (ひねらない)",
        "te": "捻って (ひねって - 촉음편)",
        "ta": "捻った (ひねった)",
        "ba": "捻れば (ひねれば)",
        "kanou": "捻れる (ひねれる)",
        "shieki": "捻らせる (ひねらせる)",
        "ukemi": "捻られる (ひねられる)",
        "ex_ja": "難しいパズルの問題に、一日中頭をひねった。",
        "ex_ko": "어려운 퍼즐 문제에 하루 종일 머리를 짜냈다."
    },
    {
        "kanji": "罵る",
        "reading": "ののしる",
        "meaning": "욕설을 퍼붓다, 매도하다",
        "category": "-いる 형태 (외형 2그룹 -> 실질 1그룹)",
        "contrast": "N2 소설·에세이 독해 빈출! ののしります / ののしらない / ののしって",
        "masu": "罵ります (ののしります)",
        "nai": "罵らない (ののしらない)",
        "te": "罵って (ののしって - 촉음편)",
        "ta": "罵った (ののしった)",
        "ba": "罵れば (ののしれば)",
        "kanou": "罵れる (ののしれる)",
        "shieki": "罵らせる (ののしらせる)",
        "ukemi": "罵られる (ののしられる)",
        "ex_ja": "激しい怒りのあまり、大声で相手を罵った。",
        "ex_ko": "극심한 분노 끝에 큰 소리로 상대를 욕하며 매도했다."
    },
    {
        "kanji": "耽る",
        "reading": "ふける",
        "meaning": "몰두하다, 빠지다 (사색·독서에)",
        "category": "-える 형태 (외형 2그룹 -> 실질 1그룹)",
        "contrast": "老ける (나이 들다, 2그룹: ふけます/ふけて)와 한자 및 활용 엄격 구분!",
        "masu": "耽ります (ふけります)",
        "nai": "耽らない (ふけらない)",
        "te": "耽って (ふけって - 촉음편)",
        "ta": "耽った (ふけった)",
        "ba": "耽れば (ふければ)",
        "kanou": "耽れる (ふけれる)",
        "shieki": "耽らせる (ふけらせる)",
        "ukemi": "耽られる (ふけられる)",
        "ex_ja": "窓の外をぼんやり見つめ、物思いに耽っていた。",
        "ex_ko": "창밖을 멍하니 바라보며 깊은 사색에 빠져 있었다."
    },
    {
        "kanji": "弄る",
        "reading": "いじる",
        "meaning": "만지작거리다, 주무르다, (재미로) 건드리다",
        "category": "-いる 형태 (외형 2그룹 -> 실질 1그룹)",
        "contrast": "スマホをいじる(스마트폰을 만지작거리다). いじります / いじって!",
        "masu": "弄ります (いじります)",
        "nai": "弄らない (いじらない)",
        "te": "弄って (いじって - 촉음편)",
        "ta": "弄った (いじった)",
        "ba": "弄れば (いじれば)",
        "kanou": "弄れる (いじれる)",
        "shieki": "弄らせる (いじらせる)",
        "ukemi": "弄られる (いじられる)",
        "ex_ja": "緊張すると、無意識に髪の毛を弄る癖がある。",
        "ex_ko": "긴장하면 무의식중에 머리카락을 만지작거리는 버릇이 있다."
    },
    {
        "kanji": "毟る",
        "reading": "むしる",
        "meaning": "쥐어뜯다, 뽑다 (털·풀 등을)",
        "category": "-いる 형태 (외형 2그룹 -> 실질 1그룹)",
        "contrast": "草をむしる(잡초를 뽑다), 毛をむしる(털을 뽑다). むしります / むしって!",
        "masu": "毟ります (むしります)",
        "nai": "毟らない (むしらない)",
        "te": "毟って (むしって - 촉음편)",
        "ta": "毟った (むしった)",
        "ba": "毟れば (むしれば)",
        "kanou": "毟れる (むしれる)",
        "shieki": "毟らせる (むしらせる)",
        "ukemi": "毟られる (むしられる)",
        "ex_ja": "休日に庭に出て、伸び放題の雑草を毟った。",
        "ex_ko": "휴일에 마당에 나가 무성하게 자란 잡초를 뽑았다."
    },
    {
        "kanji": "契る",
        "reading": "ちぎる",
        "meaning": "맹세하다, 굳게 약속하다",
        "category": "-いる 형태 (외형 2그룹 -> 실질 1그룹)",
        "contrast": "愛を契る(사랑을 맹세하다). 千切る(찢다, 1그룹)와 동음이의어!",
        "masu": "契ります (ちぎります)",
        "nai": "契らない (ちぎらない)",
        "te": "契って (ちぎって - 촉음편)",
        "ta": "契った (ちぎった)",
        "ba": "契れば (ちぎれば)",
        "kanou": "契れる (ちぎれる)",
        "shieki": "契らせる (ちぎらせる)",
        "ukemi": "契られる (ちぎられる)",
        "ex_ja": "二人はどんな困難があっても共に生きると契った。",
        "ex_ko": "두 사람은 어떤 어려움이 있더라도 함께 살아가겠다고 맹세했다."
    },
    {
        "kanji": "抉る",
        "reading": "えぐる",
        "meaning": "도려내다, 파내다, 마음을 후벼파다",
        "category": "-える 형태 (외형 2그룹 -> 실질 1그룹)",
        "contrast": "N2 소설·감정 묘사 빈출: 心をえぐる(마음을 후벼파다). えぐります / えぐって",
        "masu": "抉ります (えぐります)",
        "nai": "抉らない (えぐらない)",
        "te": "抉って (えぐって - 촉음편)",
        "ta": "抉った (えぐった)",
        "ba": "抉れば (えぐれば)",
        "kanou": "抉れる (えぐれる)",
        "shieki": "抉らせる (えぐらせる)",
        "ukemi": "抉られる (えぐられる)",
        "ex_ja": "彼の冷たい一言が、私の胸を深く抉った。",
        "ex_ko": "그의 차가운 한마디가 내 가슴을 깊숙이 후벼팠다."
    }
]

print(f"Total curated exception verbs: {len(EXCEPTION_VERBS)}")
